services:
  - type: worker
    name: celery
    region: frankfurt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A tasks worker -l info"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celeredis
          type: redis
          property: connectionString
  - type: web
    name: server
    region: frankfurt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celeredis
          type: redis
          property: connectionString
  - type: redis
    name: celeredis
    region: frankfurt
    plan: free 
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
